[build]
  publish = "Wesbite"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/properties"
  to = "/.netlify/functions/properties"
  status = 200

[[redirects]]
  from = "/api/condos"
  to = "/.netlify/functions/condos"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200
